### ISSUE TITLE
Add filter by: imdb, tmdb, original_title, certification

### ISSUE THREAD

**Issue by ticao2** [Stunkymonkey/hidaya#3]
It's not about problems.
I've been looking for an interface for newbies or older people for a while.
In my opinion Kodi is too complex for these people.
As I'm a little slow I only tested this theme of yours 2 days ago.
Despite knowing that it has been around for a long time. **:-)**
And I think it can solve my goal very well.

Just to confirm.
I tested it and I believe it worked for Filters.
Title Location - OK
File Path - OK
Collection - OK
Direction - OK
Gender - OK
Label - OK
Country - OK
Studio - OK
Year - OK
Sort by is Alphabetical Title

And it doesn't work for
Original Title - Does not filter
IMDB ID - Does not filter
TMDb ID - Does not filter
Certification - Does not filter
Sort by - Watched
Sort by - Date Added (most recent)
Sort by - Year

**Comment by Stunkymonkey** [comment]
if you want i can easily add:
- Original Title
- IMDB ID
- TMDb ID
- Certification

to sort by more filters needs more work. and i would further discuss this in #4

**Comment by ticao2** [comment]
Thanks for the quick response.  
I don't think it's necessary. Maybe some user needs the filter for Original Title.  
But IMDB ID and TMDb ID newbies don't have much idea what it is.  
And the certification I think to be useful should be something like a certification and all the below.  
That is, put 16 and see all 16, 12, 6 and 0.
And this I think is more complicated. There would need to be a Hierarchy of certifications for all countries.
For example, in my case the order would be L, 10, 12, 14, 16 and 18.
Every country will be different.
But if it is easy to implement a rule like **=<** can be useful for some countries. 
My **L** gets in the way but can be bypassed.
I even intend to suggest in the TMDb the adoption of a scale of this type.
Maybe in the future it will be implemented.
But thank you very much for the offer.
I will continue to monitor your updates.
And happy New Year. **:-)**

**Comment by ticao2** [comment]
For registration only.
Using Firefox, Win 11, when I click the Play button, if the movie file is:
MKV = open the system player.
MP4 = opens Firefox's HTML5 player. And does not display external subtitles.
To open the System Player you need to change your Firefox settings.
URL: about:config
Option: media.play-stand-alone = false

I don't know what happens to Chrome.

**Comment by Stunkymonkey** [comment]
fixed with 59d9f49921a103fca45a3e82288777ecc0ae4d5f

**Comment by ticao2** [comment]
Thank you very much. I will update. 
ORIGINAL_TITLE
IMDB_ID
TMDB_ID
STUDIOS
TAGS
DIRECTOR
WRITER
COUNTRIES
SET
CERTIFICATION

I wrongly assumed that it was possible to use whatever expression was in the path of the file. I don't think it's possible.
Although they are not in the list of class="search-attributes" they can also be used.
**Title** or **Local_Title**
**Gender**
**Year**
Can any other attributes or parameters be used ?


Thank you one more time.

**Comment by ticao2** [comment]
I installed the latest version of MediaElch.
MediaElch_win_2.8.17-dev_2022-03-21_00-12_git-master-1a81ff9d.zip
It looks like these new filters are not available.

    Original Title
    IMDB ID
    TMDb ID
    Certification

I also tried to use the version available for Download here on GithHub and I couldn't use the new filters either.

**Comment by Stunkymonkey** [comment]
then please contact the maintainer from the main repo. I am not seeing anything related in the commit messages.
