### ISSUE TITLE
No Subtitles Available

### ISSUE THREAD

**Issue by ticao2** [Stunkymonkey/hidaya#5]
No subtitles available
Win11 + MPC-HC
Apparently there was some update on Win11 and/or Firefox.
Now when I click Play it opens a window, I choose my default player and it takes a lot longer to open the movie.
Looks like some script was added.
So my Player doesn't provide option to select external .srt subtitle file.
This behavior is new.
If I open it with my default player directly in MediaElch or in File Manager this problem does not occur.
I don't know if it only happens to me or also to other users.

**Comment by Stunkymonkey** [comment]
I believe this is a browser problem and not fixable by me, since the link can only contain a single file.

**Comment by ticao2** [comment]
See here https://github.com/Stunkymonkey/hidaya/issues/6
